// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingInfo = { filename: string, path: string, size_bytes: bigint, 
/**
 * True when the file was encrypted with the vault key (AES-256-GCM v2 prefix).
 * False for recordings saved while the vault was locked, or legacy plaintext files.
 */
encrypted: boolean, };
